version: "3.9"

services:
  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pwteam12
      MYSQL_DATABASE: public
      MYSQL_USER: team12
      MYSQL_PASSWORD: pwteam12
    restart: always

  adminer:
      image: adminer
      restart: always
      ports: 
          - 8080:8080


  redisdb:
    image: redis:7.0.5
    volumes:
      - ./redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always