version: "3.9"

services:
  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./../_db/mysql/data:/var/lib/mysql
      - ./../_db/mysql/conf:/etc/mysql/conf.d
      - ./../_db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: pwteam12
      MYSQL_DATABASE: shop
      MYSQL_USER: team12
      MYSQL_PASSWORD: pwteam12
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
